import {
  ArchiveDecryptError,
  decryptHeader,
} from "@/src/model/archive/archive-crypto";
import {
  EncryptedHeaderV3,
  validateHeaderV3,
} from "@/src/model/archive/archive-format";
import { encodeBase64 } from "@/src/model/archive/archive-codec";

// ============================================================================
// Deterministic known-answer / regression fixture
// ============================================================================
describe("deterministic known-answer fixture", () => {
  // Generated by a standalone Node `crypto` script, deliberately
  // NOT via this codebase's own encryptJson — fixed generated recovery key, plaintext,
  // salt, nonce, and KDF params, frozen forever as a regression pin. See
  // AES-256-GCM (NIST SP 800-38D) and PBKDF2-HMAC-SHA256 (RFC 8018); Node's
  // `crypto.createCipheriv('aes-256-gcm', ...)` appends the auth tag the
  // same way `@noble/ciphers`' `gcm` does (tag concatenated after
  // ciphertext), so this is a genuine independent cross-check, not a
  // restatement of this file's own code.
  //
  // Regeneration script (do not run against product code — this is a
  // fixed, frozen fixture; only rerun if deliberately replacing it):
  //
  //   node -e "
  //   const crypto = require('crypto');
  //   const recoveryKey = '9a8b7c6d5e4f30211223344556677889900aabbccddeeff00112233445566778';
  //   const salt = Buffer.from('aabbccddeeff00112233445566778899', 'hex');
  //   const nonce = Buffer.from('000102030405060708090a0b', 'hex');
  //   const iterations = 600000;
  //   const key = crypto.pbkdf2Sync(recoveryKey, salt, iterations, 32, 'sha256');
  //   const fp = crypto.createHash('sha256').update(recoveryKey, 'utf8').digest('base64');
  //   const aad = Buffer.from(
  //     ['Archive-v3', 'PBKDF2-SHA256', '1', '600000', fp, salt.toString('base64'), nonce.toString('base64')].join('\\x1F'),
  //     'utf8'
  //   );
  //   const plaintext = Buffer.from(JSON.stringify({ thoughts: [{ hello: 'known-answer' }] }), 'utf8');
  //   const cipher = crypto.createCipheriv('aes-256-gcm', key, nonce);
  //   cipher.setAAD(aad);
  //   const enc = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  //   const ciphertext = Buffer.concat([enc, cipher.getAuthTag()]);
  //   console.log(JSON.stringify({ fp, salt: salt.toString('base64'), nonce: nonce.toString('base64'), ciphertext: ciphertext.toString('base64') }));
  //   "
  const knownAnswerRecoveryKey =
    "9a8b7c6d5e4f30211223344556677889900aabbccddeeff00112233445566778";
  const knownAnswerPlaintext = JSON.stringify({
    thoughts: [{ hello: "known-answer" }],
  });
  const knownAnswerHeader: EncryptedHeaderV3 = {
    v: "Archive-v3",
    kdf: "PBKDF2-SHA256",
    paramsVersion: 1,
    iterations: 600000,
    fp: "PauTTlEe/RY3eySpmyozx1qwf5LQQAiEjddbkc5Fc7o=",
    salt: "qrvM3e7/ABEiM0RVZneImQ==",
    nonce: "AAECAwQFBgcICQoL",
    ciphertext:
      "fme2k9PfVr1oKajKZOv1ro1aeGOu26VgVZ1SQKZ3dRAFimTXYW6/ZijT/sECaNzXo6AkUHmkOg==",
  };

  test("the frozen fixture header passes validateHeaderV3", () => {
    expect(validateHeaderV3(knownAnswerHeader)).toEqual({
      ok: true,
      header: expect.objectContaining({ v: "Archive-v3" }),
    });
  });

  test("this codebase's decryptHeader returns the exact known plaintext", async () => {
    const decrypted = await decryptHeader(
      knownAnswerRecoveryKey,
      knownAnswerHeader
    );
    expect(decrypted).toBe(knownAnswerPlaintext);
  });

  test("tampering with an authenticated header field fails the frozen fixture", async () => {
    const tampered = {
      ...knownAnswerHeader,
      nonce: encodeBase64(new Uint8Array(12).fill(0)),
    };
    await expect(
      decryptHeader(knownAnswerRecoveryKey, tampered)
    ).rejects.toThrow(ArchiveDecryptError);
  });
});

// ============================================================================
// Independent cross-implementation interoperability fixture
// ============================================================================

describe("independent interoperability fixture", () => {
  const independentFixtureRecoveryKey =
    "696e646570656e64656e742066697874757265207061737370687261736520313233";

  // Generated by an independent Node `crypto` script (Task 6, Step 1),
  // NOT by this codebase's own encryptJson — a shared implementation bug
  // in both encode and decode here can't hide behind a self-consistent
  // round trip. Distinct fixed inputs from the known-answer fixture above:
  // this fixture only asserts decryptHeader accepts cross-implementation
  // output, not full header/tamper coverage (that's the KAT's job).
  //
  // Regeneration recipe (keep independent of production encryptJson):
  //
  //   const crypto = require("crypto");
  //   const recoveryKey =
  //     "696e646570656e64656e742066697874757265207061737370687261736520313233";
  //   const salt = Buffer.from("0102030405060708090a0b0c0d0e0f10", "hex");
  //   const nonce = Buffer.from("101112131415161718191a1b", "hex");
  //   const iterations = 600000;
  //   const fp = crypto.createHash("sha256").update(recoveryKey, "utf8").digest("base64");
  //   const key = crypto.pbkdf2Sync(recoveryKey, salt, iterations, 32, "sha256");
  //   const aad = Buffer.from(
  //     ["Archive-v3", "PBKDF2-SHA256", "1", "600000", fp, salt.toString("base64"), nonce.toString("base64")].join("\\x1F"),
  //     "utf8"
  //   );
  //   const plaintext = Buffer.from(JSON.stringify({ thoughts: [] }), "utf8");
  //   const cipher = crypto.createCipheriv("aes-256-gcm", key, nonce);
  //   cipher.setAAD(aad);
  //   const enc = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  //   const ciphertext = Buffer.concat([enc, cipher.getAuthTag()]);
  //   console.log(JSON.stringify({
  //     fp,
  //     salt: salt.toString("base64"),
  //     nonce: nonce.toString("base64"),
  //     ciphertext: ciphertext.toString("base64"),
  //   }));
  const independentFixture: EncryptedHeaderV3 = {
    v: "Archive-v3",
    kdf: "PBKDF2-SHA256",
    paramsVersion: 1,
    iterations: 600000,
    fp: "jDGKaMnpl+21yWLeX013bzLQUOBgh4O1uOAqHLTEhn0=",
    salt: "AQIDBAUGBwgJCgsMDQ4PEA==",
    nonce: "EBESExQVFhcYGRob",
    ciphertext: "yBXk2lvolcvvkP1Cr5535IV5s/3orJIf+3ZxphI3WA==",
  };

  test("this codebase's decryptHeader accepts the independently-generated fixture", async () => {
    const decrypted = await decryptHeader(
      independentFixtureRecoveryKey,
      independentFixture
    );
    expect(JSON.parse(decrypted)).toEqual({ thoughts: [] });
  });
});
