import { create } from "zustand";
import { createJSONStorage, persist } from "zustand/middleware";
import { Distortion, DistortionData, Thought } from "@/model";
import { ensureThoughtRecordReady } from "../services/ensureThoughtRecordReady";
import { zustandMmkvStorage } from "@/services/storage/zustandStorage";
import { thoughtsService } from "../services/thoughtsService";

const slides: readonly Thought.SlideName[] = ["automatic-thought", "distortions", "challenge", "alternative-thought"];
type State = { currentSlide: Thought.SlideName; automaticThought: string; selectedDistortionSlugs: string[]; challenge: string; alternativeThought: string; setSlide(s: Thought.SlideName): void; nextSlide(): void; prevSlide(): void; setAutomaticThought(s: string): void; toggleDistortion(s: string): void; setChallenge(s: string): void; setAlternativeThought(s: string): void; isSaving: boolean; error: Error | null; saveRecord(): Promise<{ status: "saved"; thought: Thought.Thought } | { status: "empty" | "failed" }>; reset(): void };
const initial = { currentSlide: "automatic-thought" as Thought.SlideName, automaticThought: "", selectedDistortionSlugs: [] as string[], challenge: "", alternativeThought: "", isSaving: false, error: null };
export const useThoughtWizardSession = create<State>()(persist((set, get) => ({ ...initial, setSlide: (currentSlide) => set({ currentSlide }), nextSlide: () => { const i = slides.indexOf(get().currentSlide); if (i < slides.length - 1) set({ currentSlide: slides[i + 1] }); }, prevSlide: () => { const i = slides.indexOf(get().currentSlide); if (i > 0) set({ currentSlide: slides[i - 1] }); }, setAutomaticThought: (automaticThought) => set({ automaticThought }), toggleDistortion: (slug) => set(({ selectedDistortionSlugs }) => ({ selectedDistortionSlugs: selectedDistortionSlugs.includes(slug) ? selectedDistortionSlugs.filter((s) => s !== slug) : [...selectedDistortionSlugs, slug] })), setChallenge: (challenge) => set({ challenge }), setAlternativeThought: (alternativeThought) => set({ alternativeThought }), saveRecord: async () => { if (get().isSaving) return { status: "failed" }; const state = get(), spec = { automaticThought: state.automaticThought, cognitiveDistortions: Distortion.createParsers(DistortionData).fromSlugSet.decode(new Set(state.selectedDistortionSlugs)), challenge: state.challenge, alternativeThought: state.alternativeThought }; if (!Thought.isMeaningfulSpec(spec)) return { status: "empty" }; set({ isSaving: true, error: null }); const thought = Thought.create(spec, new Date()); try { await thoughtsService(DistortionData, await ensureThoughtRecordReady()).write(thought); get().reset(); return { status: "saved", thought }; } catch (error) { set({ error: error instanceof Error ? error : new Error(String(error)) }); return { status: "failed" }; } finally { set({ isSaving: false }); } }, reset: () => set(initial) }), { name: "thoughtRecord:wizard-session:v1", storage: createJSONStorage(() => zustandMmkvStorage), partialize: ({ currentSlide, automaticThought, selectedDistortionSlugs, challenge, alternativeThought }) => ({ currentSlide, automaticThought, selectedDistortionSlugs, challenge, alternativeThought }) }));
